name: flutter_boilerplate
description: Flutter boilerplate practice project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Navigation
  go_router: ^14.4.1

  # Network API
  dio: ^5.7.0
  retrofit: ^4.4.1

  # Database
  drift: ^2.21.0
  sqlite3_flutter_libs: ^0.5.26
  sqlite3: ^2.4.7
  path_provider: ^2.1.5
  path: ^1.9.1

  # Local Storage
  shared_preferences: ^2.3.2


 # UI Components
  flex_color_scheme: ^8.0.0
  auto_size_text: ^3.0.0


  # Error Tracking
  sentry_flutter: ^8.9.0
  sentry_dio: ^8.9.0
  feedback: ^3.1.0
  feedback_sentry: ^3.0.1

  # Analytics
  firebase_analytics: ^11.3.3
  mixpanel_flutter: ^2.3.3

  # Firebase
  firebase_core: ^3.6.0
  firebase_remote_config: ^5.1.3


  # Utils
  package_info_plus: ^8.1.0
  url_launcher: ^6.3.1
  force_update_helper: ^0.1.5
  in_app_review: ^2.0.9
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  logger: ^2.4.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.13
  freezed: ^2.5.7
  drift_dev: ^2.21.2
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.4
  riverpod_generator: ^2.6.2

  # Lints
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.2

  # Flavor
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.2
  flutter_flavorizr: ^2.2.3
  sentry_dart_plugin: ^2.1.0

# Flutter configuration
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/config/

# Flutter launcher icons configuration
flutter_launcher_icons:
  development:
    image_path: "assets/icons/icon_dev.png"
    android: true
    ios: true
  staging:
    image_path: "assets/icons/icon_stg.png"
    android: true
    ios: true
  production:
    image_path: "assets/icons/icon.png"
    android: true
    ios: true

# Flutter native splash configuration
flutter_native_splash:
  development:
    color: "#42a5f5"
    image: "assets/splash/splash_dev.png"
  staging:
    color: "#42a5f5"
    image: "assets/splash/splash_stg.png"
  production:
    color: "#42a5f5"
    image: "assets/splash/splash.png"